"""
Esmerald settings for src project.

Generated by 'esmerald createproject' using Esmerald 3.1.2.
"""

from typing import Optional

from esmerald.conf.enums import EnvironmentType

from ..settings import AppSettings


class TestingAppSettings(AppSettings):
    debug: bool = True
    app_name: str = "My application in testing mode."
    title: str = "My src"
    environment: Optional[str] = EnvironmentType.TESTING