"""empty message

Revision ID: 96c2ddd332e9
Revises: 
Create Date: 2024-04-13 19:10:09.464078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c2ddd332e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('ratingstars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('value', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('poster', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('world_premiere', sa.Date(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('fees_in_usa', sa.Integer(), nullable=True),
    sa.Column('fess_in_world', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=130), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=True),
    sa.Column('directors', sa.Integer(), nullable=True),
    sa.Column('actors', sa.Integer(), nullable=True),
    sa.Column('genres', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actors'], ['actors.id'], name='fk_movies_actors_id_actors', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], name='fk_movies_categories_id_category', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['directors'], ['actors.id'], name='fk_movies_actors_id_directors', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genres'], ['genres.id'], name='fk_movies_genres_id_genres', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('movies_actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie', sa.Integer(), nullable=True),
    sa.Column('actor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor'], ['actors.id'], name='fk_movies_actors_actors_id_actor', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie'], ['movies.id'], name='fk_movies_actors_movies_id_movie', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie', sa.Integer(), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre'], ['genres.id'], name='fk_movies_genres_genres_id_genre', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie'], ['movies.id'], name='fk_movies_genres_movies_id_movie', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('star', sa.Integer(), nullable=False),
    sa.Column('movie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie'], ['movies.id'], name='fk_ratings_movies_id_movie', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['star'], ['ratingstars.id'], name='fk_ratings_ratingstars_id_star', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('movie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie'], ['movies.id'], name='fk_reviews_movies_id_movie', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent'], ['reviews.id'], name='fk_reviews_reviews_id_parent', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('ratings')
    op.drop_table('movies_genres')
    op.drop_table('movies_actors')
    op.drop_table('movies')
    op.drop_table('ratingstars')
    op.drop_table('genres')
    op.drop_table('categories')
    op.drop_table('actors')
    # ### end Alembic commands ###
